const CACHEKEYS = {
    SESSION_DETAILS : "SESSION_DETAILS",
    FETCH_CHANNELS : "FETCH_CHANNELS",
    FETCH_USERS : "FETCH_USERS",
    FETCH_USAGE : "FETCH_USAGE",
    FETCH_BITRATE : "FETCH_BITRATE",
    FETCH_CHANNEL_HEALTH : "FETCH_CHANNEL_HEALTH",
    FETCH_VIEW_COUNT : "FETCH_VIEW_COUNT"
}

export default CACHEKEYS;